### ISSUE TITLE
[BUG]: 启动Docker后保存或者新增笔记就一直提示500报错

### ISSUE THREAD

**Issue by fuduoluo** [codeacme17/examor#102]
### Description of the bug

service：Log日志提示：
/usr/bin/env: ‘bash\r’: No such file or directory
/usr/bin/env: ‘bash\r’: No such file or directory

提交或者保存，点击查看ALL笔记都会提示这个
Request failed with status code 500
![image](https://github.com/codeacme17/examor/assets/34312206/83559fed-ec5b-48f0-9d8c-6ccc04d7f4e6)

**Comment by codeacme17** [comment]
@fuduoluo 请问一下你拉取的版本是多少

**Comment by fuduoluo** [comment]
> @fuduoluo请问一下你获取的版本是多少
拉取是master分支的，版本应该是最新的。

**Comment by yata0815** [comment]
@fuduoluo 你好，请问你解决了吗？

**Comment by fuduoluo** [comment]
> @fuduoluo 你好，请问你解决了吗？

没有,出错后就一直没有看了。本地docker有一个服务好像一直没有启动报错信息:/usr/bin/env: ‘bash\r’: No such file or directory,我启动环境是win10系统,具体原因不清楚是怎么回事!

**Comment by yata0815** [comment]
> > @fuduoluo 你好，请问你解决了吗？
> 
> 没有,出错后就一直没有看了。本地docker有一个服务好像一直没有启动报错信息:/usr/bin/env: ‘bash\r’: No such file or directory,我启动环境是win10系统,具体原因不清楚是怎么回事!

解决了，应该是docker images打包的时候没有bash,在server文件中的dockersfile加入RUN apt-get update && apt-get install -y bash dos2unix命令就行了

**Comment by codeacme17** [comment]
@yata0815 您是否方便可以提一个pr？ 感谢您的解决方案！
