### ISSUE TITLE
[FEAT]: Supporting openai base change or supporting python dotenv as server loading

### ISSUE THREAD

**Issue by redreamality** [codeacme17/examor#11]
### Description

# .env file 
OPENAI_API_KEY=xxx
OPENAI_API_TYPE=open_ai
OPENAI_API_BASE="xxxx"

# python file
from dotenv import load_dotenv
load_dotenv(".env")

**Comment by codeacme17** [comment]
OPENAI_API_BASE is for Azure right? I don't know whether openai also needs to set this parameter.. 
The environment variables here are all configured by the user through the client, and then I will store them in the corresponding database, and finally store them in the python environment variables

**Comment by redreamality** [comment]
you can set it either for openai.  
This is an approach to supporting calling openai API behind an enterprise gateway.

**Comment by codeacme17** [comment]
OK, i will test, thx for your enhancement.

**Comment by codeacme17** [comment]
@redreamality Thanks for the suggestion, I added the `openai_api_base` config option
