### ISSUE TITLE
[BUG]:  你的repo出现在了我的账户中，我并没有对此进行fork。

### ISSUE THREAD

**Issue by zhjrcc** [codeacme17/examor#120]
### Description of the bug

如图：
<img width="825" alt="image" src="https://github.com/user-attachments/assets/c8331ac7-bd7f-474b-a7ae-d21ad3ed93e0">
我并没有对仓库进行过fork，但之前确实提过一次issue，然后因为docker下载异常就没继续了……我今天上来才看到这个仓库怎么就直接到我仓库了，不是很理解。

**Comment by codeacme17** [comment]
idk

**Comment by zhjrcc** [comment]
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/9e2fd609-175d-436e-a012-85eae8e082c3">
我特意fork了一次……

**Comment by zhjrcc** [comment]
是不是你把我拉到了协作者去了？刚看了github文档，说是有可能是你把我错误拉到了仓库协作者？

**Comment by codeacme17** [comment]
> 是不是你把我拉到了协作者去了？刚看了github文档，说是有可能是你把我错误拉到了仓库协作者？

没有

**Comment by zhjrcc** [comment]
那就真的不清楚了，我记得我有提过一次[issue](https://github.com/codeacme17/examor/issues/26#issue-1878775379)，然后就没做什么特别的事了？直到我发现我账户中直接就有了你的仓库，并且不是fork出来的那个。我只是担心我会误操作把你仓库搞坏了，现在目前看来应该没什么问题吧？希望没事。那也就只能这样。

**Comment by codeacme17** [comment]
不会有问题
