### ISSUE TITLE
[BUG]: mac m1 startup error

### ISSUE THREAD

**Issue by richLpf** [codeacme17/examor#23]
### Description of the bug

My system version is  mac m1

node version is not support , Can be replace with `FORM node:18-alpine`
 ![image](https://github.com/codeacme17/examor/assets/22763900/33740b1e-b762-43f9-873a-fe21595eb9e8)

can't uspport mysql，Can be replaced with `FROM mariadb:latest`
![image](https://github.com/codeacme17/examor/assets/22763900/617fca8c-fa1a-4adf-bc5b-bf48562c8b3b)

After replacement, it can run normally

**Comment by codeacme17** [comment]
@richLpf，Thanks for your issue. We use the same operating system and I don't have this problem. I think it may be due to network or docker local cache problems.

**Comment by codeacme17** [comment]
Hi @richLpf, I would like to ask if the problem has been solved now. If it is solved, I will close this issue.
