### ISSUE TITLE
[BUG]: docker-compose up报错

### ISSUE THREAD

**Issue by zhjrcc** [codeacme17/examor#26]
### Description of the bug

作者，我刚下载了docker for mac的桌面版，然后按照你的文档运行`docker-compose up`之后就开始下载一堆东西，后面就开始报错了，原因我也看不太懂。新手，不知道要怎么解决了，谷歌也搜不出来答案，只能来这里寻求一下帮助了。另外，我也设置了docker的国内镜像了，也还是会报错。
<img width="1098" alt="image" src="https://github.com/codeacme17/examor/assets/81341476/72f61110-0c89-4f60-b386-e6d592cbb7df">

**Comment by codeacme17** [comment]
@zhjrcc，你好，我认为这还是网络问题导致的，你可以尝试使用其他稳定的国内镜像或者使用代理
