### ISSUE TITLE
[BUG]: 新增笔记时，报"Only '.md' type files are allowed to be uploaded"

### ISSUE THREAD

**Issue by lizhanfei** [codeacme17/examor#31]
### Description of the bug

本机环境：mac 12.6.6，chrome。
代码是9.2号最新clone下来的。
当我新增笔记的时候，会报“The type of file 'mysql的引擎和索引结构.md' is wrong, Only '.md' type files are allowed to be uploaded”
<img width="1141" alt="image" src="https://github.com/codeacme17/examor/assets/16754950/815a5a13-6a44-42d8-a3aa-2c3faf31107d">
<img width="1678" alt="image" src="https://github.com/codeacme17/examor/assets/16754950/5c44a99b-adc5-44f5-aaf0-ff40ff1c07c1">
麻烦作者看下什么原因

**Comment by codeacme17** [comment]
您可以详细看一下 #24 这个 issue 的内容， 应该是你 markdown is文件的 MIME 类型有问题。 请您先确认一下，然后我们再进一步的讨论

**Comment by codeacme17** [comment]
我会在这几天优化有关 `.md` 文件类型的判断，最晚周二会更新有关这个逻辑的代码，您如果有什么建议也可以提供给我，或者提交 PR～

**Comment by jwz520** [comment]
@codeacme17 作者你好，我好像也是这个问题，查看了md的MIME类型是text/plain，有什么方法可以设置为你服务器需要的text/markdown or text/x-markdown 类型吗？

**Comment by codeacme17** [comment]
@jwz520, 我会在今晚更新这段 [detectLegalFile](https://github.com/codeacme17/examor/blob/454b1089c5b7de4e990322a7acebd11d91c1c671/app/src/utils/detect-legal-file.ts#L9) 代码的逻辑，我刚刚将这个代码处理出来，更新后会支持其他 MIME 类型的 markdown 文件，请稍等

**Comment by codeacme17** [comment]
我更新了这部分的逻辑，请更新代码后再尝试上传

**Comment by jwz520** [comment]
@codeacme17 ,不行呀还是传不上去
![image](https://github.com/codeacme17/examor/assets/76696708/2beb0b03-e1fa-488e-95f1-d659bdf36b74)
![image](https://github.com/codeacme17/examor/assets/76696708/077c2cd8-ef8d-4fd5-ac18-42b74eb00ede)

**Comment by codeacme17** [comment]
> @codeacme17 ,不行呀还是传不上去
> 
> ![image](https://github.com/codeacme17/examor/assets/76696708/2beb0b03-e1fa-488e-95f1-d659bdf36b74)
> 
> ![image](https://github.com/codeacme17/examor/assets/76696708/077c2cd8-ef8d-4fd5-ac18-42b74eb00ede)
> 
> 
> 
> 

额 为什么你这文件 type 是空...

**Comment by lizhanfei** [comment]
> > @codeacme17 ,不行呀还是传不上去
> > ![image](https://user-images.githubusercontent.com/76696708/265295699-2beb0b03-e1fa-488e-95f1-d659bdf36b74.png)
> > ![image](https://user-images.githubusercontent.com/76696708/265296165-077c2cd8-ef8d-4fd5-ac18-42b74eb00ede.png)
> 
> 额 为什么你这文件 type 是空...

他这个信息和我这边好像是一样，type都是空，是不是操作系统或者浏览器版本不一样导致的。
作者是不是考虑不要这块限制啊？以实际内容是否可以解析为准，而不是mime类型？

**Comment by codeacme17** [comment]
其实我想过这个问题，但我又怕不使用 MIME 类型判断会出现其他的问题。我今天可以试着改变判定逻辑，等晚些时间你们在进行尝试吧

**Comment by codeacme17** [comment]
@lizhanfei, @jwz520  我更新了代码，请尝试

**Comment by jwz520** [comment]
@codeacme17 能上传了，但一直处在上传中
![image](https://github.com/codeacme17/examor/assets/76696708/3a9012a2-9cdf-4d6e-b60e-f9abef7323f3)
![image](https://github.com/codeacme17/examor/assets/76696708/031ea1cc-808e-49c0-b15a-0e6fc29601d0)

**Comment by codeacme17** [comment]
@jwz520 我想应该文件内容的问题，如果方便可以将您的文件发送到我的邮箱中么，我今天晚些时候定位一下问题。我的邮箱是 codeacme17@gmail.com

**Comment by jwz520** [comment]
@codeacme17  👌 已将文件发送到您邮箱

**Comment by codeacme17** [comment]
> @codeacme17 👌 已将文件发送到您邮箱

这个文件没有问题，应该是调用  Openai 时出现了访问接口的限制，我目前也在考虑如何能避免这个限制，比如加入队列这种方式。

**Comment by codeacme17** [comment]
> @codeacme17 能上传了，但一直处在上传中 ![image](https://user-images.githubusercontent.com/76696708/265305903-3a9012a2-9cdf-4d6e-b60e-f9abef7323f3.png) ![image](https://user-images.githubusercontent.com/76696708/265306409-031ea1cc-808e-49c0-b15a-0e6fc29601d0.png)

我创建了一个新的 issue #33 来着重解决这个报错问题，这个 issue 我将关闭，十分感谢 @lizhanfei 与 @jwz520 的协助~

**Comment by codeacme17** [comment]
@jwz520 我在 #34 这个 pr 中尝试修复了这个bug，由于我手上没有免费的 openai 账号，不太清楚是否彻底的修复了这个问题，您可以尝试更新代码，再进行上传。
