### ISSUE TITLE
[BUG]: profile中如果设置的ORGANIZATION字符串过长导致profile更新不成功

### ISSUE THREAD

**Issue by Ekkosun** [codeacme17/examor#45]
### Description of the bug

我在测试的时候无意间将organization那里填写了api-key，提交profile之后ui没有错误提示并且profile界面跟提交成功时一模一样，但是服务器端的log是
```
mysql error: 提示organization太长，无法更新数据库。 
```
然后我看了您的代码，我发现在mysql_handler这个类里面的操作虽然都进行了异常和错误的处理，但是这些错误并没有抛出进行处理，所以前端无法响应这些错误。比如说这个函数：
![1](https://github.com/codeacme17/examor/assets/43778275/20cd5f2e-8bc0-4971-8a7f-72da3f3c47c8)

（我的开发经验比较少，可能提出的意见并不好）

**Comment by codeacme17** [comment]
你好 @Ekkosun，很抱歉我并没有为用户输入的 profile 字段进行任何校验，也没有为数据库的操作异常抛出错误，我这两天会对这个问题进行更新，十分感谢你的反馈！

**Comment by Ekkosun** [comment]
哇欧，感谢你的回复（第一次提issue）。俺对这个项目也很感兴趣，感谢你的开发！

**Comment by codeacme17** [comment]
很荣幸这个项目获得了你第一个issue，同时也十分欢迎你为该项目提pr，目前 examor 还是在非常早期的阶段，有很多的地方需要优化和迭代，十分期待你的加入！
