### ISSUE TITLE
[CHAT]:After installation, there are no errors when importing the Markdown file, but the questions cannot be extracted.

### ISSUE THREAD

**Issue by eiweorerw** [codeacme17/examor#47]
### Description

I deployed a set of Docker services online, but after importing the Markdown file, it prompts for a test key and says it may take some time. However, it still cannot extract the questions. I'm not sure if it's a configuration issue or a problem with the Markdown file. I renamed a text file to an MD file and the content includes Chinese poetry and English articles.

**Comment by eiweorerw** [comment]
Upload successful. The entire process did not encounter any errors. The notes in the left sidebar can be clicked to enter, but they are empty. No questions were generated in the database, and the `is_uploading` field in the `t_file` table has been set to 0. then When starting the service today, an error occurred: "Can't connect to MySQL server on 'database:3306' (113)". However, at that time, I was able to connect to the database using Navicat from the external network.

**Comment by codeacme17** [comment]
I understand. You can try uploading this document [en-vue-props.md](https://github.com/codeacme17/examor/blob/main/docs/templates/en-vue-props.md) to see if the issue persists. Regarding the other problem, please attempt to rebuild the Docker container. As I haven't encountered this specific issue before, please check if there are any error messages in the console. If there are, please send them to me.
