### ISSUE TITLE
点击上传后一直转圈圈

### ISSUE THREAD

**Issue by DangGwanHou** [codeacme17/examor#49]
### Description of the bug

作者您好，我在昨天（21号）拉取了你最新的代码，然后运行`docker-composer up -d`，项目被正常拉取并build后能正常运行

然后我在profile一栏进行`api key`的配置，完成配置后点击提交，没有任何的提示

再回到首页新增md笔记，填写好笔记的名字和选择了md文件后，点击上传却一直在转圈圈

整个流程belike:

```mermaid
graph LR
    1(配置`api key`) --> 返回首页 --> 点击新增笔记 --> 填写笔记名称 --> 点击选择文件 --> 点击上传 --> 上传按钮转圈圈
    上传按钮转圈圈 --> 点击上传
```

**Comment by codeacme17** [comment]
Hi @DangGwanHou， 我初步预测是由于网络的原因，我这两天会尝试复现一下你的问题

**Comment by codeacme17** [comment]
我还想确认一下，你可否进入到 examor-server 这个容器中的终端，输入 `curl https://www.google.com` 看看能否是否正常返回 HTML

**Comment by DangGwanHou** [comment]
@codeacme17 作者您好，感谢你2个小时内给我的答复：
按照你的意见，我在server容器里面输入了以下指令
```shell
curl https://www.google.com
```
结果是等待5分钟后依然没有任何字符从控制台弹出

**Comment by DangGwanHou** [comment]
@codeacme17 感谢你的意见，执行`curl https://www.google.com`后结果如下：
```shell
root@946a503cb7c3:/# curl https://www.google.com
curl: (56) Received HTTP code 500 from proxy after CONNECT
```
我设置的proxy是正常的国内IP

**Comment by codeacme17** [comment]
如果想访问 openai 的接口需要设置 proxy，国内的应该不太行
