### ISSUE TITLE
有没有比较简单的教程？

### ISSUE THREAD

**Issue by YandLiu** [codeacme17/examor#53]
### Description

运行完`docker-compose up`后出现很多这个`No such file or directory`，不过可以打开那个localhost的网址
![image](https://github.com/codeacme17/examor/assets/26127104/1949aeb0-fefa-4eec-8dab-4119e9d200aa)

但是添加笔记页面提示有问题
![image](https://github.com/codeacme17/examor/assets/26127104/8691f007-5b32-482a-a9c0-25f099d26f52)
![image](https://github.com/codeacme17/examor/assets/26127104/c9e4bfdf-4381-4bc7-b3f1-50c164caffe1)

**Comment by codeacme17** [comment]
你的问题与 #21 相似，请问当前使用的 examor 是什么

**Comment by YandLiu** [comment]
最新clone的仓库

**Comment by codeacme17** [comment]
好的，500报错是因为服务器启动的问题，今晚我会尝试修复这个bug

**Comment by codeacme17** [comment]
我更新了代码，请拉取最新的代码，看看问题是否解决

**Comment by YandLiu** [comment]
没有解决，还是那两个问题
另外还有个问题，文件拖拽过去是没反应的，必须得手动点击“选择文件”才行
![2023-09-27_203056](https://github.com/codeacme17/examor/assets/26127104/057659f1-a27a-4356-945c-01f2b8238b6d)

![image](https://github.com/codeacme17/examor/assets/26127104/d5700dc0-a0b1-463b-b5b7-08d8003ef9ff)

**Comment by codeacme17** [comment]
好的，我会尽快修复这些问题
