### ISSUE TITLE
[FEAT]:关于复习算法 

### ISSUE THREAD

**Issue by whgsh** [codeacme17/examor#58]
### Description

请问有没有可能把FSRS复习算法加进来呢
https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler

**Comment by codeacme17** [comment]
hi @whgsh, 这是个很棒的提议！我会去研究一下这个算法，以考虑它是否在该项目中是否可行，感谢你的 issue

**Comment by guicaiyue** [comment]
期待
