### ISSUE TITLE
[CHAT]: 'x-ratelimit-limit-requests'

### ISSUE THREAD

**Issue by ANIIAN91** [codeacme17/examor#59]
### Description

您好，我是docker安装的程序，使用chatgpt3.5的api调用时，无论是回答还是创建笔记都会在浏览器上方'弹出x-ratelimit-limit-requests'错误，请问是什么原因？
而当我更换到chatgpt4.0的api时是可以使用的，无论是回答还是创建笔记

**Comment by codeacme17** [comment]
请问，是否可以给我一些报错信息的截图，或者报错详情，让我更好定位问题

**Comment by ANIIAN91** [comment]
很抱歉，我只能看到这些输出，但是没看到报错的问题
![image](https://github.com/codeacme17/examor/assets/50096523/63002ba6-0182-43cb-a146-e40d896208ee)
![image](https://github.com/codeacme17/examor/assets/50096523/d6fde722-cb69-415b-8726-55104803c56e)
![image](https://github.com/codeacme17/examor/assets/50096523/e466370c-cbef-419c-ab50-659787f3eb11)

api的设置
![image](https://github.com/codeacme17/examor/assets/50096523/bfc05490-2429-4233-a352-1341518720eb)

弹出的出错
![image](https://github.com/codeacme17/examor/assets/50096523/eb9917e0-6d33-46b5-bf72-0dede9ed45bd)

**Comment by codeacme17** [comment]
感谢提供的截图，请问不知道可不可以再提供一下浏览器控制台中 network 中的请求
![屏幕截图 2023-10-18 152140](https://github.com/codeacme17/examor/assets/67408722/dc0eec68-d7a7-4e96-af14-f0c29e2ee75e)
像是这样

**Comment by ANIIAN91** [comment]
![image](https://github.com/codeacme17/examor/assets/50096523/ebcb4a31-129f-4745-a08d-6195d1596a12)
这个可以吗? 还是需要固定的请求

**Comment by ANIIAN91** [comment]
![image](https://github.com/codeacme17/examor/assets/50096523/a704e6e3-dc3d-4c28-ab60-9d0dfce2a017)

抱歉 是这个

**Comment by ANIIAN91** [comment]
![image](https://github.com/codeacme17/examor/assets/50096523/a44dd825-9f7e-46f2-ac3c-c030a6f8ca8e)

![image](https://github.com/codeacme17/examor/assets/50096523/0fc59c09-9136-4d2f-975b-8f2f7f5fc562)

![image](https://github.com/codeacme17/examor/assets/50096523/98848b83-d9b6-4949-b8b1-f2556d91c19c)

**Comment by ANIIAN91** [comment]
这里有发现两个报错情况，不知道对您是否有用

这个是刷新后会出现的
![image](https://github.com/codeacme17/examor/assets/50096523/80d0eb92-abaa-4f25-820e-0df5c6aac416)


![image](https://github.com/codeacme17/examor/assets/50096523/760212d2-aef0-4151-bcb6-1f449fb03962)

**Comment by codeacme17** [comment]
> 这里有发现两个报错情况，不知道对您是否有用
> 
> 这个是刷新后会出现的 ![image](https://user-images.githubusercontent.com/50096523/276169471-80d0eb92-abaa-4f25-820e-0df5c6aac416.png)
> 
> ![image](https://user-images.githubusercontent.com/50096523/276169189-760212d2-aef0-4151-bcb6-1f449fb03962.png)
> 
> https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting API rate limit exceeded for 45.194.20.22. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

这个报错是 github 获取项目版本信息的，暂时可以忽略~

**Comment by codeacme17** [comment]
@ANIIAN91, 之前的报错应该是 Openai 对于账号的 Rate limits 引起的，详细内容可以参照 https://platform.openai.com/docs/guides/rate-limits/rate-limits。也可以尝试切换其他的账号测试，看看是否还会出现以上报错

**Comment by ANIIAN91** [comment]
好的 试过了 的确是账号问题

**Comment by codeacme17** [comment]
好的，那我将这个 issue 关闭了，感谢使用 examor！
