### ISSUE TITLE
[BUG]: 1054 (42S22): Unknown column 'anthropicModel' in 'field list'

### ISSUE THREAD

**Issue by xunone11** [codeacme17/examor#60]
### Description

添加openai api时，log日志提示
server_1    | Error: 1054 (42S22): Unknown column 'anthropicModel' in 'field list'
server_1    | INFO:     172.23.0.4:44048 - "PUT /profile HTTP/1.1" 200 OK

![图片](https://github.com/codeacme17/examor/assets/67742893/64b1a560-fb70-4525-84de-20f64f9f9139)

**Comment by codeacme17** [comment]
请问你拉取的是否是最新的版本并且更新了之前的 docker 容器

**Comment by xunone11** [comment]
容器已经删除了，可能还需要删除原来的镜像在此拉取，我再试试，我看镜像大小还蛮大的，下载的有点慢

**Comment by codeacme17** [comment]
好的，重新构建容器后应该就不会有这个问题了，我后面会尝试优化 docker 配置提升打包的速度
