### ISSUE TITLE
[BUG]: Can not add new notes

### ISSUE THREAD

**Issue by koktlzz** [codeacme17/examor#64]
### Description of the bug

I used the latest version of examor and can't add any new notes. The UI showed some error messages: `Expecting value: line 1 column 1 (char 0)`. However, I can import notes from existing question bank.
I tried many notes including the [example](https://github.com/codeacme17/examor/blob/main/docs/templates/zh-vue-props.md) but all failed.

**Comment by codeacme17** [comment]
Ok, i think its an error from database, i will try to reappear ASAP

**Comment by codeacme17** [comment]
@koktlzz, hi, i have fixed this issue on #65. you can pull the latest code, its will work

**Comment by koktlzz** [comment]
Thanks for your quickly reply. It works!
